/**
 * Development environment settings
 *
 * This file can include shared settings for a development team,
 * such as API keys or remote database passwords.  If you're using
 * a version control solution for your Sails app, this file will
 * be committed to your repository unless you add it to your .gitignore
 * file.  If your repository will be publicly viewable, don't add
 * any private information to this file!
 *
 * This file was generated by Ansible for {{ ansible_fqdn }}
 */

module.exports = {

  /***************************************************************************
   * Set the default database connection for models in the development       *
   * environment (see config/connections.js and config/models.js )           *
   ***************************************************************************/

  bootstrapTimeout: 480000,
  pubsub: {
    _hookTimeout: 480000,
  },
  log: {
    level: '{{ REDBOX_PORTAL_LOGLEVEL_DEV }}'
  },
  appUrl:'{{ HTTP_S }}://{{ FQDN }}',
  sockets: {
    beforeConnect: function(handshake, proceed) {
      // beforeConnect will make it ignore onlyAllowOrigins
      // Send back `true` to allow the socket to connect.
      // (Or send back `false` to reject the attempt.)
      return proceed(undefined, true);
    },
    onlyAllowOrigins: ["{{ HTTP_S }}://{{ FQDN }}"]
  },
  db: {
    waitRetries: 5,
    waitSleep: 10000
  },
  models:{
     migrate: 'safe'
  },
  auth: {
    // Default brand...
    default: {
      active: ["aaf", "local"],
      aaf: {
        loginUrl: "{{ REDBOX_PORTAL_AAF_LOGIN_URL }}",
        opts: {
          secretOrKey: '{{ REDBOX_PORTAL_AAF_SECRET }}',
          jsonWebTokenOptions: {
            issuer: '{{ JWT_TOKEN_ISSUER }}',
            audience: '{{ REDBOX_PORTAL_AAF_AUDIENCE }}',
            ignoreNotBefore: true
          }
        }
      },
      local: {
        usernameField: 'username',
        passwordField: 'password',
        default: {
          adminUser: 'admin',
          adminPw: '{{ REDBOX_PORTAL_ADMIN_PASSWORD }}',
          email: '{{ REDBOX_PORTAL_ADMIN_EMAIL }}'
        },
        templatePath: 'local.ejs',
        postLoginRedir: 'researcher/home',
      },
    },
    postLogoutRedir: '{{ REDBOX_PORTAL_AAF_LOGOUT_URL }}'
  },
  routes: {
    // Straight to dashboard home
    '/:branding/:portal/home': '/default/rdmp/researcher/home'
  },
  redbox: {
    apiKey: '{{ REDBOX_API_KEY }}'
  },
  mint: {
    apiKey: '{{ MINT_API_KEY }}',
    api: {
      search: {
        method: 'get',
        url: '/api/v1/search'
      }
    }
  },
  vocab: {
    providers: {
      geonames: {
        method: 'get',
        url: "{{ MINT_HTTP_S }}://{{ MINT_FQDN }}/geonames/search?func=search&q=${query}&format=json",
        options: {
        }
      }
    }
  },
  record: {
    baseUrl: {
      redbox: "{{ REDBOX_HTTP_S }}://{{ REDBOX_HOST }}/redbox",
      mint: "{{ MINT_HTTP_S }}://{{ MINT_FQDN }}/mint"
    },
    attachments: {
      stageDir: '{{ REDBOX_PORTAL_ATTACHEMENTS }}',
      path: '/attach'
    }
  },
  datastores:{
    mongodb: {
      adapter: require('sails-mongo'),
      url: 'mongodb://{{ MONGODB_CONNECTION }}:27017/redbox-portal',
      ssl: {{ MONGODB_SSL }}
    }
  },
  workspaces: {
    portal:{
      authorization: 'Bearer {{ REDBOX_PORTAL_API_KEY }}'
    },
    provisionerUser: 'admin',
    parentRecord: 'rdmp',
    omero: {
      parentRecord: 'rdmp',
      formName: 'omero-1.0-draft',
      workflowStage: 'draft',
      appName: '{{ OMERO_APP }}',
      appId: '{{ OMERO_APP_ID }}',
      recordType: '{{ OMERO_APP }}',
      host: '{{ OMERO_HOST }}',
      domain: '{{ OMERO_DOMAIN }}',
      serverId: '1',
      defaultGroupId: 1
    },
    gitlab: {
      parentRecord: 'rdmp',
      formName: 'gitlab-1.0-draft',
      workflowStage: 'draft',
      appName: '{{ GITLAB_APP }}',
      appId: '{{ GITLAB_APP_ID }}',
      recordType: 'gitlab',
      host: '{{ GITLAB_HOST }}',
    }
    {% if LABARCHIVES_HOOK_ENABLED %}
    ,
    labarchives: {
      parentRecord: 'rdmp',
      formName: 'labarchives-1.0-draft',
      workflowStage: 'draft',
      appName: 'labarchives',
      appId: 'labarchives',
      recordType: 'labarchives',
      workspaceFileName: 'README.md',
      key: { "akid": "{{ LABARCHIVES_AKID }}", "password": "{{ LABARCHIVES_API_KEY}}","baseurl": "{{ LABARCHIVES_BASEURL }}", "api": "{{ LABARCHIVES_API }}" },
      location: 'https://au-mynotebook.labarchives.com',
      description: 'eNotebook Workspace'
    }
    {% endif %}
    {% if STORAGE_HOOK_ENABLED %}
    ,
    storage: {
      parentRecord: 'rdmp',
      formName: 'storage-1.0-draft',
      workflowStage: 'draft',
      appName: 'storage',
      appId: 'storage',
      recordType: 'storage',
      workspaceFileName: 'README.md',
      types: [
        {
          name: 'testsmb',
          format: 'smb',
          label: 'smb',
          description: 'Windows Share',
          base: '/opt/testsmb'
        }, {
          name: 'testnfs',
          format: 'nfs',
          label: 'nfs',
          description: 'For Linux',
          base: '/opt/testnfs'
        }, {
          name: 'smb1',
          format: 'nfs',
          label: 'smb',
          description: 'Windows Share',
          base: '/opt/mounts/smb/smb1'
        }, {
          name: 'nfs1',
          format: 'nfs',
          label: 'nfs',
          description: 'For Linux',
          base: '/opt/mounts/nfs/nfs1'
        }
      ]
    }
    {% endif %}
    {% if REDCAP_HOOK_ENABLED %}
    ,
    redcap: {
      parentRecord: 'rdmp',
      formName: 'redcap-1.0-draft',
      workflowStage: 'draft',
      appName: 'redcap',
      appId: 'redcap',
      recordType: 'redcap',
      location: 'https://redcap.research.uts.edu.au',
      description: 'REDCap Workspace'
    }
    {% endif %}
    {% if CATALOG_HOOK_ENABLED %}
    ,
    catalog: {
      parentRecord: 'rdmp',
        formName: 'catalog-1.0-draft',
        workflowStage: 'draft',
        appName: 'catalog',
        appId: 'catalog',
        recordType: 'catalog',
        description: 'eResearch Service',
        domain: '{{ CATALOG_SERVICE_NOW }}',
        taskURL: '/task.do?sys_id=',
        requestTable: 'sc_request',
        user: '{{ CATALOG_SERVICE_NOW_USER }}',
        password: '{{ CATALOG_SERVICE_NOW_USER_PWD }}',
        openedById: 'cd9315bbdb37fb0079ca773c349619b9',
        assignedToEmail: 'anselm.motha@uts.edu.au',
        testRequestorId: null,
    }
    {% endif %}
  }
};
